version: "3"

services:
  postgress:
    image: postgres:latest
    container_name: teste-conexao-postgres2
    environment:
      POSTGRES_USER: teste2
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: teste2
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - ./teste-conexao:/var/lib/postgresql/data

volumes:
  postgres-data:
